### ISSUE TITLE
Did it work?

### ISSUE THREAD

**Issue by nikitalita** [B-Raffai/esp32-i2s-pcm3060-test#1]
Was it feasible?

**Comment by Barabas5532** [comment]
Yes, I have been using it in my real-time guitar DSP effects project. I am running a guitar amplifier and speaker simulation, chorus and noise gate effects. These use about 40% of the available CPU time to process a mono channel. It's working with no dropouts after some tweaking based on the advice here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/speed.html

Here are separate repositories for [firmware/frontend software](https://github.com/ShrapnelDSP/ShrapnelMonorepo) and [hardware](https://github.com/ShrapnelDSP/ShrapnelPCB).
